const LEVELS = [
  ['f', 'ff', 'fff'],
  ['d', 'dd','ddd'],
  ['f','d','ff','dd'],
  ['fd','df','ff','dd'],
  ['s','ss','sss','f','d'],
  ['a','aa','aaa'],
  ['a', 's', 'd', 'f'],
  ['as','sd','fd','ds','sa','aa','ss','dd','ff'],
  ['sad','sds','fad','aaa','sss','ddd','fff'],
  ['sad','fad', 'a', 'dad'],
  ['j','jj','jjj'],
  ['k','kk','kkk'],
  ['j','jj','k','kk'],
  ['j','jj','k','kk','jk','kj'],
  ['l','ll','lll','j','k'],
  ['k','kk','kkk'],
  [';',';;',';;;'],
  ['j','k','l',';'],
  ['lk','lk','jk','j','l','k',';'],
  ['f','g'],
  ['f','ff','g','gg'],
  ['f','ff','g','gg','fg','gf'],
  ['gas','gag','sag'],
  ['h','j'],
  ['h','hh','j','jj'],
  ['f','j','g','h'],
  ['f','ff','j','jj','g','gg','h','hh'],
  ['f','ff','j','jj','g','gg','h','hh','fg','gf','jh','hj'],
  ['f','ff','j','jj','g','gg','h','hh','fg','gf','gh','hg','fh','hf','jg','gj','jh','hj'],
  ['f','j','g','h','k','l','l','k','j','g','h','a','s','d','d','s','a',';'],
  ['fg','gh','hj','jf','gf','hg','jh','fj','gh','hj','jf','gf','hg','jh','fj'],
  ['gs','ga','gh','fa','fs','sg','ha','ga','gs','ga','gh','fa','fs','sg','sh','ga'],
  ['gad','gaff','gas','fad','fad','sag','hag','gag'],
  ['fads','gags','sags','hags'],
  ['gag','lad','gal','ag','ja'],
  ['r','rr','rrr'],
  ['rag', 'rad', 'far','jar'],
  ['rag', 'rad', 'far','jar','rags','jars','hard'],
  ['t','tt','ttt'],
  ['rt','tr','rt','tr','r','t'],
  ['tar','rat','tat','fat','sat','hat','that'],
  ['u','uu','uuu'],
  ['us','hut','tut'],
  ['us','hut','tut','huts','tuts','shut'],
  ['y','yy','yyy'],
  ['day', 'hay',]
  ['u','uu','y','yy'],
  ['u','uu','y','yy','uy','yu','uy','yu'],
  ['r','t','y','u'],
  ['rr','tt','yy','uu','tr','ty','uy','yu','rt','ty','uy','yu','tr','ty','uy','yu'],
  ['ra','ta','ya','ua','ar','at','ay','au','ar','at','ay','au','ar','at','ay','au'],
  ['rs','ts','ys','us','sr','st','sy','su','sr','st','sy','su','sr','st','sy','su'],
  ['rty','tu','ry','ty','rt','try','tyr','yt','rtu','urt','uty','utr','tyu','uyt','ytr','ryt','rtu','urt','uty','utr'],
  ['a','s','d','f','g','h','j','k','l',';','r','t','y','u'],
  //two letter combinations of the above
  ['aa','ss','dd','ff','gg','hh','jj','kk','ll',';;','rr','tt','yy','uu','uu','yy','tt','rr',';;','ll','kk','jj','gg','hh','ff','dd','ss','aa'],
  // mix of the above
  ['ar','at','ay','au','as','ad','ag','ah','aj','ak','al','as','ad','ag','ah','aj','ak','al'],
  ['at','rat','rag','far','rad','tar','art','at','tag','tad','far','rag'],
  ['farts','tarts','rats','tars','arts','rats','stars','starts','tags','stags','farts'],
  ['hug','bug','gut','tug','rat','hard','that','the','last','sat', 'fat','hat','hut','stat','jut'],
  ['lky','ulk','lk','hy','yh','ly','hy','yy','lly','hu','uh','ly','hy','yy','lly','hu','uh'],
  ['tags','has','last','fast','had','talk','talks','stalk','hall','shady','lasts','staff','stalk','hulky','full','hull','gull','gully','full','fully'],
  ['i','e','ii','ee', 'ie', 'ei'],
  ['d','e','k','i','ei','ie','id','di','de','ek','ke','kd','dk','ie','ei','id','di','de','ek','ke','kd','dk'],
  ['it','is','in','and', 'at', 'to', 'of'],
  ['is','the','it','if','red','tire','fit','hit','hits','farts','farted','he','she','eileen', 'dad','dads','stiff','fist', 'hi','stiff'],  
  ['v','b','n','f','g','h','j','r','t','y','u'],
  ['tut','but','tuft','gut','rut','nut','tug','hug','bug','tug','hug','bug'],
  ['q','w','e','r','t','y','u','i','o','p','q','w','e','r','t','y','u','i','o','p','a','s','d','f','g','h','j','k','l'],
  ['pup','up', 'quest', 'queen', 'pop', 'we', 'eat', 'peep', 'poop'],
  ['a','s','d','f','g','h','j','k','l','z','x','c','v','b','n','m','z','x','c','v','b','n','m'],
  ['q','w','e','r','t','y','u','i','o','p','a','s','d','f','g','h','j','k','l','z','x','c','v','b','n','m'],
  ['xray','zoo', 'bee', 'vex', 'cab', 'craze'],
  ['is','it','of','me','my','us','no','up','by','to','or','pi','in','off','lo','so','be','bi','re','do','re','mi','fa','so','la','ti','do','re','mi','fa','so','la','ti','do','re','mi','fa','so','la','ti','do','re','mi','fa','so','la','ti','do','re','mi','fa','so','la','ti'],
  [
    'the', 'of', 'to', 'and', 'a', 'in', 'is', 'it', 'you', 'that',
    'he', 'was', 'for', 'on', 'are', 'with', 'as', 'I', 'his', 'they',
    'be', 'at', 'one', 'have', 'this', 'from', 'or', 'had', 'by', 'hot',
    'word', 'but', 'what', 'some', 'we', 'can', 'out', 'other', 'were',
    'all', 'there', 'when', 'up', 'use', 'your', 'how', 'said', 'an',
    'each', 'she', 'which', 'do', 'their', 'time', 'if', 'will', 'way',
    'about', 'many', 'then', 'them', 'write', 'would', 'like', 'so',
    'these', 'her', 'long', 'make', 'thing', 'see', 'him', 'two', 'has'],
  [
    'the', 'of', 'to', 'and', 'a', 'in', 'is', 'it', 'you', 'that',
    'he', 'was', 'for', 'on', 'are', 'with', 'as', 'I', 'his', 'they',
    'be', 'at', 'one', 'have', 'this', 'from', 'or', 'had', 'by', 'hot',
    'word', 'but', 'what', 'some', 'we', 'can', 'out', 'other', 'were',
    'all', 'there', 'when', 'up', 'use', 'your', 'how', 'said', 'an',
    'each', 'she', 'which', 'do', 'their', 'time', 'if', 'will', 'way',
    'about', 'many', 'then', 'them', 'write', 'would', 'like', 'so',
    'these', 'her', 'long', 'make', 'thing', 'see', 'him', 'two', 'has',
    'look', 'more', 'day', 'could', 'go', 'come', 'did', 'number', 'sound',
    'no', 'most', 'people', 'my', 'over', 'know', 'water', 'than', 'call',
    'first', 'who', 'may', 'down', 'side', 'been', 'now', 'find', 'any',
    'new', 'work', 'part', 'take', 'get', 'place', 'made', 'live', 'where',
    'after', 'back', 'little', 'only', 'round', 'man', 'year', 'came',
    'show', 'every', 'good', 'me', 'give', 'our', 'under', 'name', 'very',
    'through', 'just', 'form', 'sentence', 'great', 'think', 'say', 'help',
    'low', 'line', 'differ', 'turn', 'cause', 'much', 'mean', 'before',
    'move', 'right', 'boy', 'old', 'too', 'same', 'tell', 'does', 'set',
    'three', 'want', 'air', 'well', 'also', 'play', 'small', 'end', 'put',
    'home', 'read', 'hand', 'port', 'large', 'spell', 'add', 'even', 'land',
    'here', 'must', 'big', 'high', 'such', 'follow', 'act', 'why', 'ask',
    'men', 'change', 'went', 'light', 'kind', 'off', 'need', 'house',
    'picture', 'try', 'us', 'again', 'animal', 'point', 'mother', 'world',
    'near', 'build', 'self', 'earth', 'father', 'head', 'stand', 'own',
    'page', 'should', 'country', 'found', 'answer', 'school', 'grow',
    'study', 'still', 'learn', 'plant', 'cover', 'food', 'sun', 'four',
    'between', 'state', 'keep', 'eye', 'never', 'last', 'let', 'thought',
    'city', 'tree', 'cross', 'farm', 'hard', 'start', 'might', 'story',
    'saw', 'far', 'sea', 'draw', 'left', 'late', 'run', 'don\'t', 'while',
    'press', 'close', 'night', 'real', 'life', 'few', 'north', 'open',
    'seem', 'together', 'next', 'white', 'children', 'begin', 'got',
    'walk', 'example', 'ease', 'paper', 'group', 'always', 'music', 'those',
    'both', 'mark', 'often', 'letter', 'until', 'mile', 'river', 'car',
    'feet', 'care', 'second', 'book', 'carry', 'took', 'science', 'eat',
    'room', 'friend', 'began', 'idea', 'fish', 'mountain', 'stop', 'once',
    'base', 'hear', 'horse', 'cut', 'sure', 'watch', 'color', 'face',
    'wood', 'main', 'enough', 'plain', 'girl', 'usual', 'young', 'ready',
    'above', 'ever', 'red', 'list', 'though', 'feel', 'talk', 'bird',
    'soon', 'body', 'dog', 'family', 'direct', 'pose', 'leave', 'song',
    'measure', 'door', 'product', 'black', 'short', 'numeral', 'class',
    'wind', 'question', 'happen', 'complete', 'ship', 'area', 'half',
    'rock', 'order', 'fire', 'south', 'problem', 'piece', 'told', 'knew',
    'pass', 'since', 'top', 'whole', 'king', 'space', 'heard', 'best',
    'hour', 'better', 'true', 'during', 'hundred', 'five', 'remember',
    'step', 'early', 'hold', 'west', 'ground', 'interest', 'reach', 'fast',
    'verb', 'sing', 'listen', 'six', 'table', 'travel', 'less', 'morning',
    'ten', 'simple', 'several', 'vowel', 'toward', 'war', 'lay', 'against',
    'pattern', 'slow', 'center', 'love', 'person', 'money', 'serve',
    'appear', 'road', 'map', 'rain', 'rule', 'govern', 'pull', 'cold',
    'notice', 'voice', 'unit', 'power', 'town', 'fine', 'certain', 'fly',
    'fall', 'lead', 'cry', 'dark', 'machine', 'note', 'wait', 'plan',
    'figure', 'star', 'box', 'noun', 'field', 'rest', 'correct', 'able',
    'pound', 'done', 'beauty', 'drive', 'stood', 'contain', 'front',
    'teach', 'week', 'final', 'gave', 'green', 'oh', 'quick', 'develop',
    'ocean', 'warm', 'free', 'minute', 'strong', 'special', 'mind',
    'behind', 'clear', 'tail', 'produce', 'fact', 'street', 'inch',
    'multiply', 'nothing', 'course', 'stay', 'wheel', 'full', 'force',
    'blue', 'object', 'decide', 'surface', 'deep', 'moon', 'island', 'foot',
    'system', 'busy', 'test', 'record', 'boat', 'common'
  ],
  ['Clark','Eileen','Paul','Dad','Mom','Lucas','Squeaky Rocket','Brownie','Flippy','Ants', 'Taylor', 'Madison', 'Alex', 'Millie', 'Vivi', 'Cactus', 'Bim']
];
  
